http:
  routers:
    pve-eranikus:
      rule: "Host(`pve-eranikus.lan.wittner.tech`)"
      entryPoints:
        - websecure
      service: pve-eranikus
      tls: {}

  services:
    pve-eranikus:
      loadBalancer:
        servers:
          - url: "https://192.168.1.11:8006"
        passHostHeader: true
        serversTransport: pve-transport

  serversTransports:
    pve-transport:
      insecureSkipVerify: true
