tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: cloudflare
        domain:
          main: "wittner.tech"
          sans:
            - "*.wittner.tech"
            - "*.lan.wittner.tech"
